# Usa a imagem oficial mais recente do PostgreSQL
FROM postgres:latest

# Define variáveis de ambiente Padrão (podem ser substituídas no docker-compose.yml ou docker run)
ENV POSTGRES_USER user_f1
ENV POSTGRES_PASSWORD password_f1
ENV POSTGRES_DB f1_silver

# Copia o script de inicialização para o diretório padrão do Docker que executa scripts na inicialização.
# O Docker automaticamente executa arquivos .sh e .sql neste diretório.
COPY init.sql /docker-entrypoint-initdb.d/